# Generated by Django 3.2.13 on 2022-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='Uid', default=1, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32, unique=True)),
                ('PassWord', models.CharField(max_length=100)),
            ],
        ),
    ]
